package io.openems.edge.controller.emergencyclustermode;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition( //
		name = "Controller Emergency Cluster Mode", //
		description = "Switches the emergency power to next storage system when battery is empty.")
@interface Config {
	String service_pid();

	String id() default "ctrlEmergencyClusterMode0";

	boolean enabled() default true;
	
	@AttributeDefinition(name = "Allow Charge from AC", description = "")
	boolean allowChargeFromAC() default true;
	@AttributeDefinition(name = "Grid Feed Limitation", description = "")
	boolean gridFeedLimitation() default true;
	@AttributeDefinition(name = "Is Remote Controlled", description = "")
	boolean isRemoteControlled() default true;
	@AttributeDefinition(name = "Remote Start", description = "")
	boolean remoteStart() default true;
	@AttributeDefinition(name = "Max Grid Feed Power", description = "")
	int maxGridFeedPower();
	@AttributeDefinition(name = "Remote Active Powerr", description = "")
	int remoteActivePower();
	
	// devices
	// Solar Log
	@AttributeDefinition(name = "PV-Inverter-ID", description = "ID of PV-Inverter device.")
	String pv_inverter_id();
	@AttributeDefinition(name = "PV-Inverter target filter", description = "This is auto-generated by 'PV-Inverter-ID'.")
	String pv_inverter_target() default "";
	
	// wago
	// Q1 - backupEssSwitch
	@AttributeDefinition(name = "Q1 IO Channel", description = "Channel address of the Q1 Digital IO that should be switched")
	String Q1_channelAddress();
	@AttributeDefinition(name = "Q1 IO component target filter", description = "This is auto-generated by 'Q1 IO Channel'.")
	String Q1_component_target() default "";
	// Q2 - primaryEssSwitch
	@AttributeDefinition(name = "Q2 IO Channel", description = "Channel address of the Q2 Digital IO that should be switched")
	String Q2_channelAddress();
	@AttributeDefinition(name = "Q2 IO component target filter", description = "This is auto-generated by 'Q2 IO Channel'.")
	String Q2_component_target() default "";
	// Q3 - pvOffGridSwitch
	@AttributeDefinition(name = "Q3 IO Channel", description = "Channel address of the Q3 Digital IO that should be switched")
	String Q3_channelAddress();
	@AttributeDefinition(name = "Q3 IO component target filter", description = "This is auto-generated by 'Q3 IO Channel'.")
	String Q3_component_target() default "";
	// Q4 - pvOnGridSwitch
	@AttributeDefinition(name = "Q4 IO Channel", description = "Channel address of the Q4 Digital IO that should be switched")
	String Q4_channelAddress();
	@AttributeDefinition(name = "Q4 IO component target filter", description = "This is auto-generated by 'Q4 IO Channel'.")
	String Q4_component_target() default "";
	
	// meters
	@AttributeDefinition(name = "Grid-Meter-ID", description = "ID of the Grid-Meter.")
	String grid_meter_id();
	@AttributeDefinition(name = "Grid-Meter target filter", description = "This is auto-generated by 'Grid-Meter-ID'.")
	String grid_meter_target() default "";
	@AttributeDefinition(name = "PV-Meter-ID", description = "ID of the PV-Meter.")
	String pv_meter_id();
	@AttributeDefinition(name = "PV-Meter target filter", description = "This is auto-generated by 'PV-Meter-ID'.")
	String pv_meter_target() default "";
	
	// esss
	@AttributeDefinition(name = "Primary-Ess-ID", description = "ID of primary Ess device.")
	String primary_ess_id();
	@AttributeDefinition(name = "Primary Ess target filter", description = "This is auto-generated by 'Primary-Ess-ID'.")
	String primary_ess_target() default "";
	@AttributeDefinition(name = "Backup-Ess-ID", description = "ID of backup Ess device.")
	String backup_ess_id();
	@AttributeDefinition(name = "Backup Ess target filter", description = "This is auto-generated by 'Backup-Ess-ID'.")
	String backup_ess_target() default "";
	
	String webconsole_configurationFactory_nameHint() default "Controller Emergency Cluster Mode [{id}]";
}
